### ISSUE TITLE
This should probably be an overloaded function named "Delete" 

### ISSUE THREAD

**Issue by kurikaesu** [DisplaySweet/portal-go#1]
https://github.com/DisplaySweet/portal-go/blob/8b8d76b5f7e2a2ad2347fe7184402525d4c6a7eb/src/accounts.go#L258

**Comment by pgmitche** [comment]
Functions with the same receiver cannot be overloaded. Functions that have the same functionality while using different receivers have had their names improved and made consistent. Issue will be closed.
