### ISSUE TITLE
Possibly put a reference to the session in the struct itself.

### ISSUE THREAD

**Issue by kurikaesu** [DisplaySweet/portal-go#2]
https://github.com/DisplaySweet/portal-go/blob/8b8d76b5f7e2a2ad2347fe7184402525d4c6a7eb/src/accounts.go#L12

When constructing the Account (and other objects), place a reference of the session into the struct so that doing operations on the object such as Update does not need to have the session as the first parameter anymore

**Comment by pgmitche** [comment]
This has been included. Closing issue.
